language: java

script:
  - echo "Skipping 3rd party tests"

before_deploy:
  - mvn package -DskipTests=true
  - chmod +x create-pcf-manifest.sh
  - ./create-pcf-manifest.sh

deploy:
  provider: cloudfoundry
  username: $CF_USERNAME
  password: $CF_PASSWORD
  api: $CF_API_HOST
  organization: $PROMREGATOR_TARGETS_ORGNAME
  space: $PCF_DEPLOYMENT_SPACE
  manifest: manifest.yml # (optional)  Defaults to manifest.yml.
  app_name: ah-poc-promregator # (optional)